---
- name: cambiar wallpaper
  hosts: all
  gather_facts: no
  tasks:
  - name: get wallpaper | sustituir por get url 
    become: true
    shell: wget http://{{ repo_host }}/files/1.png -O /tmp/wall.png
  - name: gsettings | cambiar por gsetting
    shell: gsettings set org.gnome.desktop.background picture-uri "file:///tmp/wall.png"
