---
- name: Instalar java
  hosts: all
  become: True
  gather_facts: no
  tasks:
  - name: apt update
    shell: apt update
  - name: install by apt
    apt:
      name: openjdk-8-jre-headless
      state: present

