---
- name: Instala SAP 
  hosts: client
  tasks:
  - name: create directory pemex
    become: true
    file:
      path: /pemex
      state: directory
      mode: '0755'
  - name: Download SAP ZIP
    get_url:
    url: http://192.168.122.246/SAPClients.tar.xz
    dest: /pemex/SAPClients.tar.xz
    mode: '0440'
  - name: Decomprimir
    unarchive:
     src: /pemex/SAPClients.tar.gz
     dest: /opt/
     remote_src: yes
  - name: Download SAP
    get_url:
     url: http://192.168.122.246/PlatinGUI750_PL1_for_Linux.JAR
     dest: /pemex/PlatinGUI750_PL1_for_Linux.JAR
     mode: '0440'
  - name: install general
    shell: java -jar PlatinGUI750_PL1_for_Linux.JAR
    args:
      chdir: /pemex
  - name: mueve a opt
    shell: mv /pemex/SAPClients /opt
  - name: remove tar
    shell: rm /pemex/sap.tar.xz
